In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.5.0'

In [3]:
data= pd.read_csv('train.csv')

In [4]:
data

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [5]:
data=data.drop(['Cabin','Name','Ticket'],axis=1)

In [6]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
dtype: int64

In [7]:
data=data.dropna(axis=0)

In [8]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [9]:
data.corr()

PassengerId  Survived    Pclass  ...     SibSp     Parch      Fare
PassengerId     1.000000  0.029526 -0.035609  ... -0.082704 -0.011672  0.009655
Survived        0.029526  1.000000 -0.356462  ... -0.015523  0.095265  0.266100
Pclass         -0.035609 -0.356462  1.000000  ...  0.065187  0.023666 -0.552893
Age             0.033681 -0.082446 -0.365902  ... -0.307351 -0.187896  0.093143
SibSp          -0.082704 -0.015523  0.065187  ...  1.000000  0.383338  0.139860
Parch          -0.011672  0.095265  0.023666  ...  0.383338  1.000000  0.206624
Fare            0.009655  0.266100 -0.552893  ...  0.139860  0.206624  1.000000

[7 rows x 7 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Pclass       712 non-null    int64  
 3   Sex          712 non-null    object 
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64  
 6   Parch        712 non-null    int64  
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB


In [11]:
data

PassengerId  Survived  Pclass     Sex  ...  SibSp  Parch     Fare  Embarked
0              1         0       3    male  ...      1      0   7.2500         S
1              2         1       1  female  ...      1      0  71.2833         C
2              3         1       3  female  ...      0      0   7.9250         S
3              4         1       1  female  ...      1      0  53.1000         S
4              5         0       3    male  ...      0      0   8.0500         S
..           ...       ...     ...     ...  ...    ...    ...      ...       ...
885          886         0       3  female  ...      0      5  29.1250         Q
886          887         0       2    male  ...      0      0  13.0000         S
887          888         1       1  female  ...      0      0  30.0000         S
889          890         1       1    male  ...      0      0  30.0000         C
890          891         0       3    male  ...      0      0   7.7500         Q

[712 rows x 9 columns]

In [12]:
x=data.iloc[:,2:].values
y=data.iloc[:,1].values

In [13]:
x[0]

array([3, 'male', 22.0, 1, 0, 7.25, 'S'], dtype=object)

In [14]:
y

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,1] = le.fit_transform(x[:, 1])

In [16]:
x[0]

array([3, 1, 22.0, 1, 0, 7.25, 'S'], dtype=object)

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [18]:

x[0]

array([0.0, 0.0, 1.0, 3, 1, 22.0, 1, 0, 7.25], dtype=object)

In [19]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x)

In [20]:
X_train[0]

array([-0.47261792, -0.20232566,  0.53403984,  0.90859974,  0.75613751,
       -0.52766856,  0.52251079, -0.50678737, -0.51637992])

In [21]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy','mse'])

In [27]:
ann.fit(X_train, y, batch_size = 32, epochs = 100)

Epoch 1/100
23/23 [==============================] - 1s 2ms/step - loss: 0.6562 - accuracy: 0.7079 - mse: 0.2315
Epoch 2/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6157 - accuracy: 0.7331 - mse: 0.2122
Epoch 3/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5820 - accuracy: 0.7612 - mse: 0.1964
Epoch 4/100
23/23 [==============================] - 0s 1ms/step - loss: 0.5527 - accuracy: 0.7725 - mse: 0.1833
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5278 - accuracy: 0.7781 - mse: 0.1726
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.7739 - mse: 0.1647
Epoch 7/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4922 - accuracy: 0.7781 - mse: 0.1587
Epoch 8/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4806 - accuracy: 0.7879 - mse: 0.1544
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 0.4722 - accuracy: 0.78

In [28]:
x_test=pd.read_csv('test.csv')

In [29]:
x_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [30]:
x_test=x_test.drop(['Cabin','Name','Ticket'],axis=1)

In [31]:
x_test=x_test.fillna(x_test.mean())

In [32]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Sex          418 non-null    object 
 3   Age          418 non-null    float64
 4   SibSp        418 non-null    int64  
 5   Parch        418 non-null    int64  
 6   Fare         418 non-null    float64
 7   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB


In [33]:
xt=x_test.iloc[:,1:].values

In [34]:
xt[:,1] = le.fit_transform(xt[:, 1])

In [35]:
xt= np.array(ct.transform(xt))
xt = sc.transform(xt)

In [36]:
y_pred = ann.predict(xt)

In [37]:
len(y_pred)

418

In [38]:
len(x_test['PassengerId'])

418

In [39]:
y_pred

array([[0.02253714],
       [0.4090482 ],
       [0.05282196],
       [0.13761753],
       [0.3489702 ],
       [0.12302628],
       [0.3955542 ],
       [0.10685238],
       [0.6465967 ],
       [0.02788767],
       [0.18178034],
       [0.20989144],
       [0.97526276],
       [0.05873039],
       [0.9810517 ],
       [0.9352136 ],
       [0.04311615],
       [0.27955964],
       [0.36784136],
       [0.37007493],
       [0.45414823],
       [0.47312328],
       [0.98878586],
       [0.8325531 ],
       [0.91437554],
       [0.02872929],
       [0.99213576],
       [0.26204866],
       [0.30226275],
       [0.08190948],
       [0.05935955],
       [0.04637787],
       [0.23040077],
       [0.24995911],
       [0.54205984],
       [0.28931105],
       [0.46823055],
       [0.54656005],
       [0.10610935],
       [0.5169821 ],
       [0.12645671],
       [0.60442436],
       [0.09987915],
       [0.9391498 ],
       [0.9822689 ],
       [0.10371482],
       [0.35938677],
       [0.021

In [40]:
pred=[np.round(i) for i in y_pred]

In [41]:
pred

[array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], d

In [42]:
ps=[i for i in x_test['PassengerId']]

In [43]:
ps

[892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1

In [44]:
sub = [[ps[i],pred[i]] for i in range(len(pred))]

In [45]:
sub

[[892, array([0.], dtype=float32)],
 [893, array([0.], dtype=float32)],
 [894, array([0.], dtype=float32)],
 [895, array([0.], dtype=float32)],
 [896, array([0.], dtype=float32)],
 [897, array([0.], dtype=float32)],
 [898, array([0.], dtype=float32)],
 [899, array([0.], dtype=float32)],
 [900, array([1.], dtype=float32)],
 [901, array([0.], dtype=float32)],
 [902, array([0.], dtype=float32)],
 [903, array([0.], dtype=float32)],
 [904, array([1.], dtype=float32)],
 [905, array([0.], dtype=float32)],
 [906, array([1.], dtype=float32)],
 [907, array([1.], dtype=float32)],
 [908, array([0.], dtype=float32)],
 [909, array([0.], dtype=float32)],
 [910, array([0.], dtype=float32)],
 [911, array([0.], dtype=float32)],
 [912, array([0.], dtype=float32)],
 [913, array([0.], dtype=float32)],
 [914, array([1.], dtype=float32)],
 [915, array([1.], dtype=float32)],
 [916, array([1.], dtype=float32)],
 [917, array([0.], dtype=float32)],
 [918, array([1.], dtype=float32)],
 [919, array([0.], dtype=flo

In [46]:
df=pd.DataFrame(sub, columns=['PassengerId','Survived'])

In [47]:
df

PassengerId Survived
0            892    [0.0]
1            893    [0.0]
2            894    [0.0]
3            895    [0.0]
4            896    [0.0]
..           ...      ...
413         1305    [0.0]
414         1306    [1.0]
415         1307    [0.0]
416         1308    [0.0]
417         1309    [0.0]

[418 rows x 2 columns]

In [48]:
for i in range(0,418):
  df["Survived"][i]=df["Survived"][i][0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [49]:
df["Survived"]

0      0
1      0
2      0
3      0
4      0
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: object

In [50]:
df

PassengerId Survived
0            892        0
1            893        0
2            894        0
3            895        0
4            896        0
..           ...      ...
413         1305        0
414         1306        1
415         1307        0
416         1308        0
417         1309        0

[418 rows x 2 columns]

In [51]:
import csv
df.to_csv('submission.csv')

In [52]:
df

PassengerId Survived
0            892        0
1            893        0
2            894        0
3            895        0
4            896        0
..           ...      ...
413         1305        0
414         1306        1
415         1307        0
416         1308        0
417         1309        0

[418 rows x 2 columns]